# docker-compose.yml
version: '3.8'

services:
  mongodb:
    image: mongo:4.2
    container_name: trading-journal-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: 1234 

    volumes:
      - mongodb_data:/data/db 

    networks:
      - trading-journal-network

  mongo-express:
    image: mongo-express:latest # Utiliza la última imagen oficial de Mongo Express.
    container_name: trading-journal-mongo-express # Nombre legible para el contenedor de Mongo Express.
    restart: always # Asegura que se reinicie si falla.
    ports:
      # Mapea el puerto 8081 del host al puerto 8081 del contenedor.
      # Mongo Express por defecto escucha en el puerto 8081.
      # Podrás acceder a la interfaz en http://localhost:8081 desde tu navegador.
      - "8081:8081"
    environment:
      # Configuración de la conexión de Mongo Express a tu servicio MongoDB.
      # 'mongodb' aquí es el nombre del servicio MongoDB en Docker Compose.
      ME_CONFIG_MONGODB_SERVER: mongodb # Hostname del servidor MongoDB (el nombre del servicio Docker Compose)
      ME_CONFIG_MONGODB_PORT: 27017 # Puerto de MongoDB

      # ¡¡¡CORRECCIÓN AQUÍ!!! Credenciales para que Mongo Express se conecte a MongoDB como ADMIN.
      # Estas deben COINCIDIR con MONGO_INITDB_ROOT_USERNAME y MONGO_INITDB_ROOT_PASSWORD del servicio 'mongodb'.
      ME_CONFIG_MONGODB_ADMINUSERNAME: user
      ME_CONFIG_MONGODB_ADMINPASSWORD: 1234

      # ¡¡¡NUEVAS LÍNEAS!!! Credenciales para el inicio de sesión en la interfaz web de Mongo Express.
      # ¡IMPORTANTE! Crea credenciales DIFERENTES a las de la base de datos para el login de Mongo Express.
      ME_CONFIG_BASICAUTH_USERNAME: admin # Usuario para acceder a la interfaz web de Mongo Express
      ME_CONFIG_BASICAUTH_PASSWORD: 1234 # Contraseña para acceder a la interfaz web de Mongo Express

      # Habilita el acceso a la administración de Mongo Express (opcional, pero útil para ver dbs).
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"

    depends_on:
      # Asegura que el servicio 'mongodb' esté iniciado antes que 'mongo-express'.
      - mongodb
    networks:
      # Conecta Mongo Express a la misma red para comunicarse con MongoDB.
      - trading-journal-network


  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: trading-journal-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://user:1234@mongodb:27017/trading_journal?authSource=admin
    depends_on:
      - mongodb

    networks:
      - trading-journal-network

volumes:
  mongodb_data:

networks:
  trading-journal-network:
    driver: bridge
